version: '3.7'

services:
  yii2-app:
    image: your-dockerhub-username/yii2-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
