- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
    update_cache: yes

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
